combine_control_expr = false
force_explicit_abi = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Auto"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true